audit/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^topics/(?P<unpass_id>\d+)/$', views.topics, name='topics'),
    url('^new_topic/(?P<unpass_id>\d+)/$', views.new_topic, name='new_topic'),
    url('^follow/(?P<topic_id>\d+)/$', views.follow, name='follow'),
    url('^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url('^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    url('^del_entry/(?P<entry_id>\d+)/$', views.del_entry, name='del_entry'),
]

corp_qa/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('dw_query.urls', 'dw_query'))),
    path('', include(('audit.urls', 'audit'))),
    path('', include(('users.urls', 'users'))),
    path('', include(('visual.urls', 'visual'))),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

dw_query/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^up(?P<batch>.+)/$', views.unpass, name='unpass'),
    url(r'^p(?P<keyword>.+)/$', views.performance, name='performance'),
    url(r'^$', views.index, name='index'),
    url(r'^search$', views.home_search, name='home_search'),
    url(r'^all_unpass$', views.all_unpass, name='all_unpass'),
    url(r'^all_suggestion$', views.all_suggestion, name='all_suggestion'),
    url(r'^dw_api$', views.chat_reply, name='chat_reply'),
]

audit/models.py
from django.db import models
from dw_query.models import UnPass


class AuditTopic(models.Model):
    unpass = models.ForeignKey(to=UnPass, to_field='id', on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    from_user = models.CharField(max_length=10)
    to_part = models.CharField(max_length=10)
    sugg_act = models.TextField()
    file = models.FileField(upload_to='files/topics/%Y%m%d', null=True, blank=True)
    image = models.ImageField(upload_to='images/topics/%Y%m%d', null=True, blank=True)

    def __str__(self):
        return self.sugg_act


class Entry(models.Model):
    topic = models.ForeignKey(AuditTopic, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    from_part = models.CharField(max_length=10)
    act = models.TextField()
    file = models.FileField(upload_to='files/entries/%Y%m%d', null=True, blank=True)
    image = models.ImageField(upload_to='images/entries/%Y%m%d', null=True, blank=True)

    def __str__(self):
        return self.act

dw_query/models.py
# -*- coding: utf-8 -*-
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class UnPass(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True)
    up_type = models.CharField(db_column='不良品种类', max_length=10)
    customer = models.CharField(db_column='客户', max_length=30)
    up_name = models.CharField(db_column='不良品名称', max_length=30)
    batch = models.CharField(db_column='批号', max_length=20)
    pro_date = models.DateField(db_column='生产日期')
    pro_qty = models.FloatField(db_column='数量Kg')  # Field name made lowercase.
    up_desc = models.TextField(db_column='不合格描述')
    result_ana = models.TextField(db_column='原因分析')
    correct_act = models.TextField(db_column='纠正措施')
    pre_act = models.TextField(db_column='预防措施')
    tech_idea = models.TextField(db_column='技术部意见')
    process_idea = models.TextField(db_column='工艺部意见')
    qa_idea = models.TextField(db_column='质量部意见')
    serv_idea = models.TextField(db_column='技术支持部意见')

    class Meta:
        managed = False
        db_table = '不合格品登记'


class UpStatus(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True)
    caseto_by_qa = models.CharField(db_column='caseto_by_QA', max_length=10)
    case_closed_flag = models.IntegerField(db_column='case_closed_flag')

    class Meta:
        managed = False
        db_table = '状态标记'


class ProInfo(models.Model):
    batch = models.CharField(db_column='批号', primary_key=True, max_length=30)
    customer = models.CharField(db_column='客户', max_length=30)
    pro_type = models.CharField(db_column='产品型号', max_length=30)
    pro_color = models.CharField(db_column='颜色', max_length=10)
    pro_date = models.DateField(db_column='生产日期')
    test_date = models.DateField(db_column='检验日期')

    class Meta:
        managed = False
        db_table = '产品信息'


class Performance(models.Model):
    batch = models.CharField(db_column='批号', max_length=30)
    extruder_skin = models.IntegerField(db_column='表面判定')
    perf = models.CharField(db_column='性能判定', max_length=4)
    rosh = models.IntegerField(db_column='RoSH')
    density = models.FloatField(db_column='密度')
    lsqd = models.FloatField(db_column='拉伸强度')
    dlscl = models.FloatField(db_column='断裂伸长率')
    dcwd = models.IntegerField(db_column='低冲温度')
    dlgs = models.IntegerField(db_column='断裂根数')
    tjdzlwd = models.IntegerField(db_column='体积电阻率温度')
    tjdzl = models.BigIntegerField(db_column='体积电阻率')
    ydbz = models.CharField(db_column='硬度标准', max_length=2)
    yd = models.FloatField(db_column='硬度')
    time200c = models.IntegerField(db_column='200℃热稳定时间')
    jdqd = models.IntegerField(db_column='介电强度')
    yzs = models.FloatField(db_column='氧指数')
    rrzs = models.FloatField(db_column='熔融指数')
    kssfcd = models.FloatField(db_column='快速水分测定')
    rbxwd = models.CharField(db_column='热变形温度', max_length=3)
    rbx = models.FloatField(db_column='热变形')

    class Meta:
        managed = False
        db_table = '常规性能'


class Parts(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    part = models.CharField(db_column='部门', max_length=10)

    class Meta:
        managed = False
        db_table = '部门'
        unique_together = (('id', 'part'),)


class JokeUrls(models.Model):
    user = models.CharField(max_length=32)
    url = models.CharField(max_length=150)


class OcrEvent(models.Model):
    from_user = models.CharField(max_length=32)
    create_time = models.CharField(max_length=16)

dw_query/forms.py
from django import forms
from .models import UnPass


class ParseUp(forms.ModelForm):
    class Meta:
        model = UnPass
        fields = ['result_ana', 'correct_act', 'pre_act',
                  'tech_idea', 'process_idea', 'qa_idea',
                  'serv_idea']
        labels = {
            'result_ana': '原因分析',
            'correct_act': '纠正措施',
            'pre_act': '预防措施',
            'tech_idea': '技术部意见',
            'process_idea': '工艺部意见',
            'qa_idea': '质量部意见',
            'serv_idea': '技术支持部意见',
        }
        widgets = {
            'result_ana': forms.Textarea(attrs={'rows': 3}),
            'correct_act': forms.Textarea(attrs={'rows': 3}),
            'pre_act': forms.Textarea(attrs={'rows': 3}),
            'tech_idea': forms.Textarea(attrs={'rows': 3}),
            'process_idea': forms.Textarea(attrs={'rows': 3}),
            'qa_idea': forms.Textarea(attrs={'rows': 3}),
            'serv_idea': forms.Textarea(attrs={'rows': 3}),
        }

dw_query/views.py
from urllib.parse import urljoin

from django.views.decorators.csrf import csrf_exempt

from .ocr import BdOCR, AppID, API_Key, Secret_Key
from . import BizWxUtil, jokes
from . import models, serial
from audit.models import AuditTopic

from django.db import connection
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required


@login_required
def index(request):
    upstatus = models.UpStatus.objects.filter(
        caseto_by_qa__isnull=False).order_by('-id')[:3]
    ids = [upstatu.id for upstatu in upstatus]
    ups = models.UnPass.objects.filter(id__in=ids)

    topics = AuditTopic.objects.all().order_by('-date_added')[:3]
    ids = [topic.unpass_id for topic in topics]
    ups_topics = models.UnPass.objects.filter(id__in=ids)

    context = {'upstatus': upstatus, 'ups': ups, 'topics': topics, 'ups_topics': ups_topics}
    return render(request, 'dw_query/index.html', context=context)


@login_required
def all_suggestion(request):
    up_id = request.GET.get('up_id', '')
    to_part = request.GET.get('to_part', '')
    customer = request.GET.get('customer', '')
    proname = request.GET.get('proname', '')
    uptype = request.GET.get('uptype', '')

    to_part = '' if to_part == '--select--' else to_part
    uptype = '' if uptype == '全部类型' or uptype is None else uptype

    if any([up_id, to_part]):
        topics = AuditTopic.objects.filter(
            to_part__contains=to_part).order_by('-date_added')
        if up_id:
            topics = topics.filter(
                unpass_id=up_id).order_by('-id')
        ids = [topic.unpass_id for topic in topics]
        ups = models.UnPass.objects.filter(id__in=ids)
        params = ['{}={}'.format(k, v) for k, v in
                  {'up_id': up_id,
                   'to_part': request.GET.get('to_part', '')
                   }.items()]
    else:
        ups = models.UnPass.objects.filter(
            up_type__contains=uptype).filter(
            customer__contains=customer).filter(
            up_name__contains=proname)
        ids = [up.id for up in ups]
        topics = AuditTopic.objects.filter(
            unpass_id__in=ids).order_by('-date_added')
        params = ['{}={}'.format(k, v) for k, v in
                  {'customer': customer,
                   'proname': proname,
                   'uptype': request.GET.get('uptype', '')
                   }.items()]

    paginator = Paginator(topics, 4)
    page = request.GET.get('page')
    topics_pgd = paginator.get_page(page)

    parts = (part.part for part in models.Parts.objects.all())
    context = {'parts': parts, 'topics': topics_pgd, 'ups_topics': ups, 'params': params}
    return render(request, 'dw_query/all_suggestion.html', context=context)


@login_required
def all_unpass(request):
    customer = request.GET.get('customer', '')
    proname = request.GET.get('proname', '')
    uptype = request.GET.get('uptype', '')
    uptype = '' if uptype == '全部类型' else uptype

    params = ['{}={}'.format(k, v) for k, v in
              {'customer': customer, 'proname': proname,
               'uptype': request.GET.get('uptype', '')}.items()]

    ups = models.UnPass.objects.filter(
        up_type__contains=uptype).filter(
        customer__contains=customer).filter(
        up_name__contains=proname)
    ids = [up.id for up in ups]
    upstatus = models.UpStatus.objects.filter(id__in=ids).order_by('-id')

    paginator = Paginator(upstatus, 4)
    page = request.GET.get('page')
    upstatus_pgd = paginator.get_page(page)

    context = {'upstatus': upstatus_pgd, 'ups': ups, 'params': params}
    return render(request, 'dw_query/all_unpass.html', context=context)


@login_required
def unpass(request, batch):
    uplist = models.UnPass.objects.filter(batch__contains=batch)
    cols = ['ID', '类型', '客户', '产品名称', '批号', '生产日期', '数量KG', '不合格原因']
    serializer = serial.DwQuerySerializer(uplist, many=True)
    data = [dic.values() for dic in serializer.data]  # serializer.data is a list comps of OrderDict
    context = {'serializer': data, 'cols': cols}
    return render(request, 'dw_query/showtbl.html', context=context)


@login_required
def performance(request, keyword):
    pro_info = ('客户', '产品型号', '颜色', '生产日期')
    test_items = (
        '批号', '表面判定', 'RoSH', '性能判定', '密度', '拉伸强度', '断裂伸长率', '低冲温度',
        '断裂根数', '体积电阻率温度', '体积电阻率', '硬度标准', '硬度', '200℃热稳定时间',
        '介电强度', '氧指数', '熔融指数', '快速水分测定', '热变形温度', '热变形')
    cursor = connection.cursor()
    sql = "SELECT {0},a.批号,IF(表面判定=TRUE,'PASS',IF(表面判定 IS NULL,NULL,'UNPASS'))," \
          "IF(RoSH=TRUE,'PASS',IF(RoSH IS NULL,NULL,'UNPASS'))," \
          "{1} FROM 产品信息 a INNER JOIN 常规性能 b ON a.批号=b.批号 " \
          "WHERE CONCAT(客户,产品型号,颜色,b.批号) like '%{2}%' order by 生产日期 DESC" \
          "".format(','.join(pro_info),
                    ','.join(test_items[3:]), keyword)
    cursor.execute(sql)
    results = cursor.fetchall()
    serializer = []
    for line in results:
        new_line = []
        for v in line:
            if isinstance(v, int) and len(str(v)) > 5:
                v = '%.2e' % v
            new_line.append('/' if v is None else str(v))
        serializer.append(new_line)
    context = {'serializer': serializer, 'cols': pro_info + test_items}
    return render(request, 'dw_query/showtbl.html', context=context)


@login_required
def home_search(request):
    keyword = request.GET.get('keyword')
    if keyword.lower().startswith('up') and len(keyword) > 2:
        return HttpResponseRedirect(reverse('dw_query:unpass', args=[keyword[2:]]))
    elif keyword.lower().startswith('p') and len(keyword) > 1:
        return HttpResponseRedirect(reverse('dw_query:performance', args=[keyword[1:]]))
    else:
        return render(request, 'dw_query/key_error.html')


@csrf_exempt
def chat_reply(request):
    if 'echostr' in request.GET:  # 响应微信验证url
        return BizWxUtil.responseEcho(request)
    if request.method == 'POST':
        message = BizWxUtil.parseMessage(request)
        keyword = message.get('Content', '').lower()
        resp_dict = {'to_user': message['FromUserName'],
                     'from_user': message['ToUserName'],
                     'type': 'text'}
        content = ''
        if message.get('EventKey') == 'how_query':
            content = '''(1) p + “<客户名>或<产品名>或<批号>”: 获取检测数据查询网址；\n(2) up + “<批号>”: 获取该批次不良信息；\nTips：如果微信浏览器不能打开，请选择其它浏览器打开！'''
        elif message.get('EventKey') == 'get_joke':
            url = r'http://xiaodiaodaya.cn/wapindex.aspx?classid=602'
            content = jokes.gen_joke(url, user=resp_dict['to_user'])
        elif keyword:
            if any([keyword.startswith('p') and len(keyword) > 1,
                    keyword.startswith('up') and len(keyword) > 2]):
                query_url = 'http://%s/search?keyword=' % request.META['HTTP_HOST']
                query_url = urljoin(query_url, keyword)
                pic_url = urljoin('http://%s' % request.META['HTTP_HOST'],
                                  'static/dw_query/query_pic.jpg')
                resp_dict['type'] = 'news'
                resp_dict['data'] = [
                    {'title': '您正在查询检测数据 + 关键字<%s>' % keyword[1:] if keyword.startswith('p') else '您正在查询不良品记录 + 关键字<%s>' % keyword[2:],
                     'description': '请点击进入网页查看结果！',
                     'pic_url': pic_url,
                     'url': query_url},
                ]
        elif message.get('EventKey') == 'ocr_read':
            ocr_event = models.OcrEvent()
            ocr_event.from_user = message.get('FromUserName')
            ocr_event.create_time = message.get('CreateTime')
            ocr_event.save()

        elif message.get('MsgType') == 'image':
            event_img = models.OcrEvent.objects.filter(
                from_user=message.get('FromUserName'))
            create_time = message.get('CreateTime')
            if (create_time,) in event_img.values_list('create_time'):
                txt = '未能成功，请重试！'
                try:
                    ocr = BdOCR(AppID, API_Key, Secret_Key)
                    words = ocr.read_words(message.get('PicUrl'))
                    lines = [line['words'] for line in words]
                    assert len(lines) > 0
                    txt = '\n'.join(lines)
                    event_img.filter(create_time=create_time).delete()
                except Exception:
                    pass
                finally:
                    content = txt
        else:
            pass
        resp_dict['content'] = content
        return BizWxUtil.parseResponse(resp_dict)

dw_query/templates/dw_query/all_suggestion.html
{% extends "dw_query/base.html" %}
{% block title %}
    <title>建议项目录</title>
{% endblock %}
{% load static %}

{% block content %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <form class="form-inline my-2 my-lg-0" action="{% url 'dw_query:all_suggestion' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="text" value="{{ request.GET.up_id }}" placeholder="不合格品ID" aria-label="Search" name="up_id">
            <label for="uptype">部门:</label>
            <select class="mr-lg-3" id="uptype" name="to_part">
                <option>--select--</option>
                {% for part in parts %}
                    <option {% ifequal request.GET.to_part part %}selected{% endifequal %}>{{ part }}</option>
                {% endfor %}
            </select>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索一</button>
        </form>
        <form class="form-inline my-2 my-lg-0" action="{% url 'dw_query:all_suggestion' %}">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="text" value="{{ request.GET.customer }}" placeholder="客户" aria-label="Search" name="customer">
            <input class="form-control mr-sm-2" type="text" value="{{ request.GET.proname }}" placeholder="产品名称" aria-label="Search" name="proname">
            <label for="uptype">不合格类型:</label>
            <select class="mr-lg-3" id="uptype" name="uptype">
                <option {% ifequal request.GET.uptype '制程不合格' %}selected{% endifequal %}>制程不合格</option>
                <option {% ifequal request.GET.uptype '退货不合格' %}selected{% endifequal %}>退货不合格</option>
                <option {% ifequal request.GET.uptype '全部类型' %}selected{% endifequal %}>全部类型</option>
            </select>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索二</button>
        </form>

        {% for topic in topics %}
            <div class="media text-muted pt-3">
                <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" focusable="false" role="img" aria-label="Placeholder: 32x32">
                    <rect width="100%" height="100%" fill="#007bff"/>
                    <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
                </svg>
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark">{{ topic.sugg_act|linebreaks }}</strong>
                        <a href="{% url 'audit:follow' topic.id %}" target="_blank">Follow({{ topic.entry_set.count }})</a>
                    </div>
                {% for up_topic in ups_topics %}
                    {% ifequal up_topic.id topic.unpass_id %}
                        <span class="d-block">
                            <a href="{% url 'audit:topics' topic.unpass_id %}" target="_blank">@Case ID<{{ topic.unpass_id }}>: </a>
                            {{ up_topic.pro_date }}生产的：{{ up_topic.customer }}-{{ up_topic.up_name }}（批号：{{ up_topic.batch }}）{{ up_topic.up_type }}>>>{{ up_topic.up_desc }}
                        </span>
                    {% endifequal %}
                {% endfor %}
                    <span class="d-block"><a style="color: #cc1111">@{{ topic.to_part }}</a> {{ topic.date_added|date:'Y-m-d H:i' }}</span>
                </div>
            </div>
        {% empty %}
            <h6 class="border-bottom border-gray pb-2 mb-0">暂时还没有任何行动建议。</h6>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="row">
            {% if topics.has_previous %}
                <a href="?page=1&{{ params|join:'&' }}" class="page-link">&laquo; First</a>
                <a href="?page={{ topics.previous_page_number }}&{{ params|join:'&' }}" class="page-link">Previous</a>
            {% endif %}
            <span class="page-link">
                Page {{ topics.number }} of {{ topics.paginator.num_pages }}.
            </span>
            {% if topics.has_next %}
                <a href="?page={{ topics.next_page_number }}&{{ params|join:'&' }}" class="page-link">Next</a>
                <a href="?page={{ topics.paginator.num_pages }}&{{ params|join:'&' }}" class="page-link">Last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock content %}

dw_query/templates/dw_query/all_unpass.html
{% extends "dw_query/base.html" %}
{% block title %}
    <title>不合格目录</title>
{% endblock %}
{% load static %}
{% block content %}
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <form class="form-inline my-2 my-lg-0" action="{% url 'dw_query:all_unpass' %}">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="text" value="{{ request.GET.customer}}" placeholder="客户" aria-label="Search" name="customer">
        <input class="form-control mr-sm-2" type="text" value="{{ request.GET.proname }}" placeholder="产品名称" aria-label="Search" name="proname">
	<input class="form-control mr-sm-2" type="text" value="{{ request.GET.batch }}" placeholder="批号" aria-label="Search" name="batch">
        <label for="uptype">不合格类型:</label>
        <select class="mr-lg-3" id="uptype" name="uptype">
	    <option {% ifequal request.GET.uptype '全部类型' %}selected{% endifequal %}>全部类型</option>
            <option {% ifequal request.GET.uptype '制程不合格' %}selected{% endifequal %}>制程不合格</option>
            <option {% ifequal request.GET.uptype '退货不合格' %}selected{% endifequal %}>退货不合格</option> 
        </select>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
    </form>
    {% for status in upstatus %}
      <a href="{% url 'audit:topics' status.id %}" target="_blank"><div class="media text-muted pt-3">
        <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" focusable="false" role="img" aria-label="Placeholder: 32x32">
            <title>点击进入</title>
                <rect width="100%" height="100%" fill="#e83e8c"/>
        </svg>
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">@{{ status.caseto_by_qa }} ID:{{ status.id }}</strong>
        {% for up in ups %}
          {% ifequal up.id status.id %}
            {{ up.pro_date }}生产的：{{ up.customer }}-{{ up.up_name }}（批号：{{ up.batch }}）{{ up.up_type }}>>>{{ up.up_desc }}
            <p style="color: #e83e8c">Suggestions({{ up.audittopic_set.count }})</p>
          {% endifequal %}
        {% endfor %}
      </div></a>
    {% endfor %}
  </div>
  <div class="pagination">
    <span class="row">
        {% if upstatus.has_previous %}
            <a href="?page=1&{{ params|join:'&' }}" class="page-link">&laquo; First</a>
            <a href="?page={{ upstatus.previous_page_number }}&{{ params|join:'&' }}" class="page-link">Previous</a>
        {% endif %}
        <span class="page-link">
            Page {{ upstatus.number }} of {{ upstatus.paginator.num_pages }}.
        </span>
        {% if upstatus.has_next %}
            <a href="?page={{ upstatus.next_page_number }}&{{ params|join:'&' }}" class="page-link">Next</a>
            <a href="?page={{ upstatus.paginator.num_pages }}&{{ params|join:'&' }}" class="page-link">Last &raquo;</a>
        {% endif %}
    </span>
  </div>
{% endblock content %}

dw_query/templates/dw_query/index.html
{% extends "dw_query/base.html" %}
{% block title %}
    <title>Home Page</title>
{% endblock %}

{% block content %}
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0" style="color: #e83e8c;font-size: large">Recent UnPass</h6>
      {% for status in upstatus %}
          <a href="{% url 'audit:topics' status.id %}" target="_blank"><div class="media text-muted pt-3">
            <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" focusable="false" role="img" aria-label="Placeholder: 32x32">
                <title>点击进入</title>
                    <rect width="100%" height="100%" fill="#e83e8c"/>
            </svg>
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">@{{ status.caseto_by_qa }} ID:{{ status.id }}</strong>
            {% for up in ups %}
              {% ifequal up.id status.id %}
                {{ up.pro_date }}生产的：{{ up.customer }}-{{ up.up_name }}（批号：{{ up.batch }}）{{ up.up_type }}>>>{{ up.up_desc }}
                <p style="color: #e83e8c">Suggestions({{ up.audittopic_set.count }})</p>
              {% endifequal %}
            {% endfor %}
          </div></a>
      {% endfor %}
    <small class="d-block text-right mt-3">
      <a href="{% url 'dw_query:all_unpass' %}" style="color: royalblue;font-size: large">Search more ...</a>
    </small>
  </div>
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0" style="color: #007bff;font-size: large"> Recent actions for Internal Audit</h6>
    {% for topic in topics %}
        <div class="media text-muted pt-3">
            <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" focusable="false" role="img" aria-label="Placeholder: 32x32">
                <rect width="100%" height="100%" fill="#007bff"/>
                <text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text>
            </svg>
            <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <div class="d-flex justify-content-between align-items-center w-100">
                    <strong class="text-gray-dark">{{ topic.sugg_act|linebreaks }}</strong>
                    <a href="{% url 'audit:follow' topic.id %}" target="_blank">Follow({{ topic.entry_set.count }})</a>
                </div>
            {% for up_topic in ups_topics %}
                {% ifequal up_topic.id topic.unpass_id %}
                    <span class="d-block">
                        <a href="{% url 'audit:topics' topic.unpass_id %}" target="_blank">@Case ID<{{ topic.unpass_id }}>: </a>
                        {{ up_topic.pro_date }}生产的：{{ up_topic.customer }}-{{ up_topic.up_name }}（批号：{{ up_topic.batch }}）{{ up_topic.up_type }}>>>{{ up_topic.up_desc }}
                    </span>
                {% endifequal %}
            {% endfor %}
                <span class="d-block"><a style="color: #cc1111">@{{ topic.to_part }}</a> {{ topic.date_added|date:'Y-m-d H:i' }}</span>
            </div>
        </div>
    {% empty %}
        <h6 class="border-bottom border-gray pb-2 mb-0">暂时还没有任何行动建议。</h6>
    {% endfor %}
    <small class="d-block text-right mt-3">
      <a href="{% url 'dw_query:all_suggestion' %}" style="color: royalblue;font-size: large">All suggestions ...</a>
    </small>
  </div>
{% endblock content %}